
package org.dcm4che3.tool.unvscp.gui;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pavel Varzinov <varzinov@yandex.ru>
 */
public class ActivityWindow extends javax.swing.JFrame {

    /**
     * Creates new form ActivityWindow
     */
    public ActivityWindow() {
        initComponents();

        /* Setting the window icon */
        URL imgUrl = getClass().getClassLoader().getResource("org/dcm4che3/tool/unvscp/icons/icon.png");
        if (imgUrl != null) {
            setIconImage(new ImageIcon(imgUrl).getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScroll = new javax.swing.JScrollPane();
        activityTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EMSOW Bridge Activity Monitor");
        setPreferredSize(new java.awt.Dimension(500, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        activityTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        activityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"04/21/2014", "JACILLA, LYNN", "05/23/1954", "CAROTID",  new Integer(21), "Long text"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Patient name", "Date of birth", "Study", "Images", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        activityTable.setRowHeight(24);
        tableScroll.setViewportView(activityTable);
        activityTable.getColumnModel().getColumn(0).setMinWidth(85);
        activityTable.getColumnModel().getColumn(0).setMaxWidth(85);
        activityTable.getColumnModel().getColumn(1).setMinWidth(100);
        activityTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        activityTable.getColumnModel().getColumn(1).setMaxWidth(200);
        activityTable.getColumnModel().getColumn(2).setMinWidth(85);
        activityTable.getColumnModel().getColumn(2).setMaxWidth(85);
        activityTable.getColumnModel().getColumn(3).setMinWidth(85);
        activityTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        activityTable.getColumnModel().getColumn(3).setMaxWidth(150);
        activityTable.getColumnModel().getColumn(4).setMinWidth(55);
        activityTable.getColumnModel().getColumn(4).setMaxWidth(55);
        activityTable.getColumnModel().getColumn(5).setMinWidth(150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int res = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to quit?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION
        );
        if (res == JOptionPane.YES_OPTION) {
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ActivityWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activityTable;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
